export const destinationData = {
  'united-states': {
    name: 'United States',
    slug: 'united-states',
    image: '🇺🇸',
    color: 'from-blue-600 to-blue-400',
    backgroundImage: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1200&h=600&fit=crop',
    universities: 2500,
    topUniversities: ['Harvard', 'MIT', 'Stanford', 'Yale', 'Princeton'],
    overview: 'The United States offers world-class education with diverse programs, exceptional research facilities, and strong career opportunities. American universities are renowned for their innovation and global recognition.',
    applyCost: {
      applicationFee: '$50-$150 per university',
      testingCosts: '$200-$300 (SAT/ACT)',
      englishTest: '$150-$190 (TOEFL)',
      processingTime: '4-8 weeks',
    },
    visaInfo: {
      type: 'F-1 Student Visa',
      processingTime: '2-4 weeks',
      documents: [
        'Valid passport (6 months validity)',
        'I-20 form from university',
        'Proof of financial support',
        'Proof of English proficiency',
        'Bank statements and financial documents',
      ],
      fees: '$160-$190',
      validity: '4 years (extensible)',
    },
    requirements: [
      'High school diploma or equivalent',
      'SAT/ACT scores',
      'TOEFL/IELTS scores',
      'Statement of Purpose (SOP)',
      'Letters of Recommendation (3)',
      'Academic transcripts',
    ],
    faq: [
      {
        question: 'How long does the US visa process take?',
        answer: 'The F-1 visa process typically takes 2-4 weeks. It\'s recommended to start the process 3 months before your intended enrollment date.',
      },
      {
        question: 'Can international students work in the US?',
        answer: 'Yes, on-campus employment is allowed up to 20 hours per week during the academic session. CPT and OPT programs allow off-campus work after graduation.',
      },
      {
        question: 'What is the average cost of studying in the US?',
        answer: 'Annual costs range from $45,000 to $80,000+ depending on the university and program. This includes tuition, accommodation, and living expenses.',
      },
      {
        question: 'Do I need GMAT/GRE for master\'s programs?',
        answer: 'Most universities require standardized test scores. Some programs may waive this requirement based on your academic record and experience.',
      },
      {
        question: 'How long can I stay in the US after graduation?',
        answer: 'You can stay for up to 12 months (STEM fields: 24-36 months) on Optional Practical Training (OPT) to gain work experience.',
      },
    ],
    timeline: [
      { month: 'Jan-Mar', task: 'Prepare for standardized tests and English exams' },
      { month: 'Apr-Jun', task: 'Research universities and prepare applications' },
      { month: 'Jul-Aug', task: 'Submit applications to universities' },
      { month: 'Sep-Dec', task: 'Receive admission decisions and select university' },
      { month: 'Jan-Feb', task: 'Apply for F-1 visa with I-20 document' },
      { month: 'Mar-Aug', task: 'Visa interview and approval' },
      { month: 'Aug-Sep', task: 'Travel to US and begin studies' },
    ],
  },
  'united-kingdom': {
    name: 'United Kingdom',
    slug: 'united-kingdom',
    image: '🇬🇧',
    color: 'from-red-600 to-red-400',
    backgroundImage: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&h=600&fit=crop',
    universities: 150,
    topUniversities: ['Oxford', 'Cambridge', 'LSE', 'Imperial College', 'UCL'],
    overview: 'UK universities are world-renowned for academic excellence, prestigious qualifications, and a rich educational heritage. Study in a country that has shaped global education for centuries.',
    applyCost: {
      applicationFee: '$0-$50',
      testingCosts: '$150-$200 (GRE/GMAT)',
      englishTest: '$150-$200 (IELTS)',
      processingTime: '4-6 weeks',
    },
    visaInfo: {
      type: 'Student Visa (Tier 4)',
      processingTime: '3-4 weeks',
      documents: [
        'Valid passport (minimum 6 months)',
        'Acceptance letter from university',
        'Proof of financial support',
        'English language proficiency certificate',
        'Bank statements and sponsor documentation',
      ],
      fees: '$500-$1,000',
      validity: 'Duration of course + 4 months',
    },
    requirements: [
      'A-Levels, IB, or equivalent qualification',
      'IELTS/TOEFL scores (minimum 6.0-6.5)',
      'University-specific entrance exams (some universities)',
      'Strong academic record',
      'Letters of recommendation',
      'Personal statement',
    ],
    faq: [
      {
        question: 'How much does it cost to study in the UK?',
        answer: 'International students pay £15,000-£40,000+ per year depending on the program. Living costs in London and other major cities are £12,000-£15,000 annually.',
      },
      {
        question: 'Can I work while studying in the UK?',
        answer: 'Yes, international students can work up to 20 hours per week during term time and full-time during holidays on their student visa.',
      },
      {
        question: 'What is the UK student visa processing time?',
        answer: 'The standard processing time is 3-4 weeks, but it\'s advisable to apply 3 months before your course starts.',
      },
      {
        question: 'Do I need to take IELTS if English is my first language?',
        answer: 'No, if you studied in English at secondary school level or higher, you may be exempt from taking IELTS.',
      },
      {
        question: 'Can I stay in the UK after my studies?',
        answer: 'Yes, you can apply for a Graduate visa which allows you to stay for 2 years to work in the UK.',
      },
    ],
    timeline: [
      { month: 'Aug-Sep', task: 'Prepare for entrance exams and IELTS/TOEFL' },
      { month: 'Sep-Oct', task: 'Apply through UCAS (undergraduate) or directly (postgraduate)' },
      { month: 'Oct-Mar', task: 'Wait for admission decisions' },
      { month: 'Mar-Jun', task: 'Receive offers and firm your choice' },
      { month: 'Jun-Jul', task: 'Gather visa documents and apply for Student Visa' },
      { month: 'Jul-Aug', task: 'Visa approval and accommodation confirmation' },
      { month: 'Aug-Sep', task: 'Travel to UK and begin studies' },
    ],
  },
  'canada': {
    name: 'Canada',
    slug: 'canada',
    image: '🇨🇦',
    color: 'from-red-500 to-orange-400',
    backgroundImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop',
    universities: 100,
    topUniversities: ['University of Toronto', 'UBC', 'McGill', 'McMaster', 'Alberta'],
    overview: 'Canada offers high-quality education at affordable costs with excellent post-graduation work opportunities. Canadian qualifications are globally recognized and valued by employers.',
    applyCost: {
      applicationFee: '$50-$150 per university',
      testingCosts: '$150-$250',
      englishTest: '$150-$200 (IELTS)',
      processingTime: '4-8 weeks',
    },
    visaInfo: {
      type: 'Study Permit',
      processingTime: '4-6 weeks',
      documents: [
        'Acceptance letter from Canadian institution',
        'Valid passport',
        'Proof of financial support (CAD 20,000-30,000+)',
        'English language proficiency',
        'Medical examination (if required)',
      ],
      fees: 'CAD $150',
      validity: 'Duration of studies + 3 months',
    },
    requirements: [
      'High school diploma',
      'English/French language proficiency (IELTS 6.0+)',
      'Academic transcripts',
      'Letters of recommendation',
      'Statement of Purpose',
      'Proof of financial support',
    ],
    faq: [
      {
        question: 'What are the costs of studying in Canada?',
        answer: 'Tuition ranges from CAD 15,000-25,000+ per year. Total annual costs (including accommodation) are approximately CAD 25,000-40,000.',
      },
      {
        question: 'Can international students work in Canada?',
        answer: 'Yes, students can work up to 20 hours per week during studies and full-time during scheduled breaks.',
      },
      {
        question: 'What is the post-graduation work permit?',
        answer: 'International graduates can get a Post-Graduation Work Permit (PGWP) for 8 months to 3 years depending on their study duration.',
      },
      {
        question: 'Is Canada a good country for permanent residence?',
        answer: 'Yes, Canada has favorable immigration policies for international graduates, making it easier to transition to permanent residency.',
      },
      {
        question: 'What is the student visa processing time for Canada?',
        answer: 'Standard processing time is 4-6 weeks. It\'s recommended to apply 4-6 months before your intended study start date.',
      },
    ],
    timeline: [
      { month: 'Jan-Mar', task: 'Prepare for IELTS and research universities' },
      { month: 'Mar-May', task: 'Submit applications to Canadian universities' },
      { month: 'May-Jul', task: 'Receive admission decisions and accept offer' },
      { month: 'Jul-Aug', task: 'Apply for Study Permit with acceptance letter' },
      { month: 'Aug-Sep', task: 'Receive Study Permit and arrange accommodation' },
      { month: 'Aug-Sep', task: 'Book flights and prepare for arrival' },
      { month: 'Sep', task: 'Arrive and begin studies' },
    ],
  },
  'australia': {
    name: 'Australia',
    slug: 'australia',
    image: '🇦🇺',
    color: 'from-yellow-600 to-orange-500',
    backgroundImage: 'https://images.unsplash.com/photo-1523482580672-f67fbdf45479?w=1200&h=600&fit=crop',
    universities: 43,
    topUniversities: ['Melbourne', 'Sydney', 'ANU', 'UNSW', 'Monash'],
    overview: 'Australia combines world-class education with a high standard of living and excellent post-study work opportunities. Study in a safe, multicultural environment with stunning natural beauty.',
    applyCost: {
      applicationFee: 'AUD 50-100',
      testingCosts: 'AUD 200-300',
      englishTest: 'AUD 200-250 (IELTS)',
      processingTime: '2-4 weeks',
    },
    visaInfo: {
      type: 'Student Visa (Subclass 500)',
      processingTime: '4-12 weeks',
      documents: [
        'Confirmation of Enrolment (CoE)',
        'Valid passport',
        'Proof of financial capacity (AUD 25,000-30,000+)',
        'English language proficiency',
        'Health examination and insurance',
      ],
      fees: 'AUD $620',
      validity: 'Duration of course + 6 months',
    },
    requirements: [
      'High school completion or equivalent',
      'IELTS minimum 5.5 (or equivalent)',
      'Academic transcripts',
      'Letters of reference',
      'English language certificate',
      'Genuine Temporary Entrant (GTE) evidence',
    ],
    faq: [
      {
        question: 'What is the cost of living in Australia?',
        answer: 'Monthly living expenses range from AUD 1,500-2,500 depending on the city. Sydney and Melbourne are generally more expensive than regional areas.',
      },
      {
        question: 'Can I work while studying in Australia?',
        answer: 'Yes, international students can work up to 20 hours per week during study periods and full-time during scheduled breaks.',
      },
      {
        question: 'What is the post-study work visa?',
        answer: 'Graduates can apply for a Post-Study Work Visa allowing them to stay and work for 18 months to 3 years depending on their qualification.',
      },
      {
        question: 'Is health insurance mandatory?',
        answer: 'Yes, all international students must have Overseas Student Health Cover (OSHC) as a visa requirement.',
      },
      {
        question: 'How long does the Australian student visa take?',
        answer: 'Processing time is typically 4-12 weeks. Apply 3-4 months before your intended start date for better chances.',
      },
    ],
    timeline: [
      { month: 'Jan-Mar', task: 'Research universities and prepare IELTS' },
      { month: 'Mar-Jun', task: 'Submit applications to Australian universities' },
      { month: 'Jun-Aug', task: 'Receive offers and accept enrollment' },
      { month: 'Aug-Sep', task: 'Apply for Student Visa with CoE' },
      { month: 'Sep-Dec', task: 'Visa processing and approval' },
      { month: 'Dec-Jan', task: 'Arrange accommodation and health insurance' },
      { month: 'Jan-Feb', task: 'Arrive in Australia and commence studies' },
    ],
  },
  'europe': {
    name: 'Europe',
    slug: 'europe',
    image: '🇪🇺',
    color: 'from-purple-600 to-pink-400',
    backgroundImage: 'https://images.unsplash.com/photo-1504681869696-d977e9d34c1d?w=1200&h=600&fit=crop',
    universities: 500,
    topUniversities: ['ETH Zurich', 'TUM', 'KU Leuven', 'Sorbonne', 'University of Heidelberg'],
    overview: 'Europe offers diverse educational programs, rich cultural experiences, and affordable tuition fees in many countries. Explore world-class universities while experiencing multiple cultures.',
    applyCost: {
      applicationFee: '€0-100 per university',
      testingCosts: '€150-200',
      englishTest: '€150-200 (IELTS/TOEFL)',
      processingTime: '4-8 weeks',
    },
    visaInfo: {
      type: 'Student Residence Permit / Schengen Visa',
      processingTime: '4-8 weeks',
      documents: [
        'Admission letter from European university',
        'Valid passport',
        'Proof of financial means (€800-1,500/month)',
        'Health insurance (mandatory)',
        'Accommodation proof',
      ],
      fees: '€0-150 (varies by country)',
      validity: 'Duration of studies',
    },
    requirements: [
      'High school completion or equivalent',
      'Language proficiency (English or local language)',
      'Academic transcripts',
      'English language test (some programs)',
      'Motivation letter',
      'References',
    ],
    faq: [
      {
        question: 'How expensive is studying in Europe?',
        answer: 'Tuition ranges from free (Germany, Nordic countries) to €10,000+ per year depending on the country and program. Living costs vary from €800-1,500/month.',
      },
      {
        question: 'Can I work while studying in Europe?',
        answer: 'Yes, most countries allow students to work part-time (15-20 hours/week). Work rights vary by country and visa type.',
      },
      {
        question: 'Is the Schengen visa required for all European countries?',
        answer: 'Most European countries are Schengen members, but some countries (UK, Ireland) have different visa systems. Check specific country requirements.',
      },
      {
        question: 'What is the language requirement for studying in Europe?',
        answer: 'Many universities offer programs in English, but proficiency in the local language may be required for some programs or for working.',
      },
      {
        question: 'Can I travel freely in Europe as a student?',
        answer: 'Yes, Schengen visa holders can travel freely within Schengen countries. Plan trips during scheduled breaks.',
      },
    ],
    timeline: [
      { month: 'Sep-Oct', task: 'Research European universities and programs' },
      { month: 'Oct-Dec', task: 'Prepare application documents and English test' },
      { month: 'Dec-Feb', task: 'Submit applications to European universities' },
      { month: 'Feb-Apr', task: 'Receive admission decisions' },
      { month: 'Apr-May', task: 'Accept offer and arrange finances' },
      { month: 'May-Jul', task: 'Apply for student residence permit/Schengen visa' },
      { month: 'Jul-Sep', task: 'Visa approval and travel to Europe' },
    ],
  },
  'singapore': {
    name: 'Singapore',
    slug: 'singapore',
    image: '🇸🇬',
    color: 'from-green-600 to-emerald-400',
    backgroundImage: 'https://images.unsplash.com/photo-1522035335684-63c27983c0c0?w=1200&h=600&fit=crop',
    universities: 6,
    topUniversities: ['NUS', 'NTU', 'SUSS', 'LASALLE', 'MDIS'],
    overview: 'Singapore offers a world-class education system in a safe, multicultural hub. Study in Asia\'s leading educational destination with strong connections to major employers.',
    applyCost: {
      applicationFee: 'SGD 20-50 per university',
      testingCosts: 'SGD 200-300',
      englishTest: 'SGD 150-200 (IELTS)',
      processingTime: '2-4 weeks',
    },
    visaInfo: {
      type: 'Student\'s Pass',
      processingTime: '4-8 weeks',
      documents: [
        'Offer letter from Singapore institution',
        'Valid passport (6 months minimum)',
        'Proof of financial support (SGD 20,000+)',
        'Medical examination',
        'Health insurance',
      ],
      fees: 'SGD 90',
      validity: 'Duration of course + 1 month',
    },
    requirements: [
      'High school diploma or GCE O-Levels',
      'English language proficiency',
      'Academic transcripts and certificates',
      'Letter of recommendation',
      'Passport validity of 6 months',
      'Health declaration',
    ],
    faq: [
      {
        question: 'What is the tuition cost in Singapore?',
        answer: 'Tuition ranges from SGD 15,000-40,000 per year depending on the institution and program. Singapore is relatively affordable compared to other developed countries.',
      },
      {
        question: 'Can international students work in Singapore?',
        answer: 'Yes, students can work part-time up to 16 hours per week. Full-time work is allowed during official school holidays.',
      },
      {
        question: 'How long can I stay after graduation?',
        answer: 'You can apply for an Employment Pass allowing you to stay and work for up to 2-3 years depending on your qualifications.',
      },
      {
        question: 'Is Singapore safe for international students?',
        answer: 'Yes, Singapore is one of the safest countries in the world with excellent public transportation and reliable infrastructure.',
      },
      {
        question: 'What is the cost of living in Singapore?',
        answer: 'Monthly living expenses are approximately SGD 1,500-2,000 including accommodation, food, and transportation.',
      },
    ],
    timeline: [
      { month: 'Jan-Mar', task: 'Research Singapore universities and programs' },
      { month: 'Mar-May', task: 'Prepare documents and English language test' },
      { month: 'May-Jul', task: 'Submit applications to Singapore institutions' },
      { month: 'Jul-Sep', task: 'Receive admission decisions and accept offer' },
      { month: 'Sep-Oct', task: 'Apply for Student\'s Pass with offer letter' },
      { month: 'Oct-Nov', task: 'Student\'s Pass approval' },
      { month: 'Nov-Jan', task: 'Arrange accommodation and travel to Singapore' },
    ],
  },
};

export type DestinationKey = keyof typeof destinationData;
